### ISSUE TITLE
Fail TravisCI if a new exercise is added without a stub file

### ISSUE THREAD

**Issue by benreyn** [exercism/elisp#124]
Ref #123 and https://github.com/exercism/discussions/issues/238. When this decision was made we already had stub files for all exercises. We should add to this a change to our CI script that will fail if a new exercise is added without a stub file.

**Comment by guygastineau** [comment]
I would think that if you want this kind of assurance from travis, then it should fail if any exercise directory is missing a stub file instead of just testing for new ones.  This will incidentally also make the logic for implementing the script easier to handle.

I am willing to write a script for it if you are still interested.

**Comment by benreyn** [comment]
Absolutely! I think my intent here is more along the lines of what you are suggesting. Recently we addressed #123 and as a part of that, wanted to ensure that we didnt create new exercises with that didnt meet this requirement. We should absolutely check for regressions as well.

**Comment by guygastineau** [comment]
Cool. I'll write a script for it.

**Comment by guygastineau** [comment]
The PR is #129
